### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by tyler-maxwell** [tyler-maxwell/project1#4]
## User Story
As a user, I want to be able to create an account and keep a record of my card collection and decks

## Acceptance Criteria
- [x] Build a form to create an account.
- [x] Build a form to login to an existing account.
- [x] When logged in, display a button (or similar element) that when clicked will display the user's owned cards.
- [x] Build a form for the user to create a new deck.
- [x] Dynamically display buttons (or similar elements) for all decks created by the user that when clicked will display the cards in that deck.

**Comment by MrMrP** [comment]
Create Account form and Login Form have been created. Now working to store/retrieve/compare Usernames with database for validation during account creation and to enable user login. Upon login user data will be stored via localstorage.

**Comment by MrMrP** [comment]
All set on my end. Working on Local storage for login. Also will adding code for a display that will show "hello 'username'" after login
